version: '3'
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD:   ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: mydb
      MARIADB_USER:  ${DB_USER}
      MARIADB_PASSWORD:  ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - "${HOME}/kiwi_data/DB:/var/lib/mysql"
