version: '3.9'
services:
  test_mariadb:
    container_name: mariadb2
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD:   ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: mydb
      MARIADB_USER:  ${DB_USER}
      MARIADB_PASSWORD:  ${DB_PASSWORD}
    ports:
      - 3307:3306
    volumes:
      - type: bind
        source: $HOME/kiwi_data/DB
        target: /var/lib/mysql
    networks:
      - test

  jaeger:
    image: "jaegertracing/all-in-one:1.6"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "6831:6831/udp" # accept jaeger.thrift over compact thrift protocol
      - "6832:6832/udp" # accept jaeger.thrift over binary thrift protocol
      - "5778:5778" # serve configs
      - "16686:16686" # serve frontend
      - "4317:4317" # accept OpenTelemetry Protocol (OTLP) over gRPC, if enabled
      - "4318:4318" # accept OpenTelemetry Protocol (OTLP) over HTTP, if enabled
      - "14250:14250" # accept model.proto
      - "14268:14268" # accept jaeger.thrift directly from clients
      - "14269:14269"
      - "9411:9411" # Zipkin compatible endpoint
    networks:
      - test

networks:
  test:
    name: my_test_net
    driver: bridge
