version: '3'
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: db_name
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    expose:
      - 3306
    volumes:
      - "${HOME}/kiwi_data/DB:/var/lib/mysql"
    networks:
      - jg

  springboot-app:
#    image: openjdk:8-jdk-alpine
#    volumes:
#      - ./app:/app
#    ports:
#      - 8080:8080
#    working_dir: /app
#    command: >
#      sh -c "java -jar my-spring-app.jar"

    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/db_name
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      GOOGLE_AUTH_CLIENT_ID: ${GOOGLE_AUTH_CLIENT_ID}
      GOOGLE_ACCESS_SECRET: ${GOOGLE_ACCESS_SECRET}
      GOOGLE_AUTH_CALLBACK_URL: ${GOOGLE_AUTH_CALLBACK_URL}
      JWTKEY: ${ACCESS_SECRET}
    ports:
      - 8080:8080
    volumes:
      - ./backend/src:/my_backend/src
    networks:
      - jg

  react-app:
    container_name: frontend
    restart: always
    environment:
      - REACT_APP_HOST=${SERVER_HOST}
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    build:
      context: ./front
      dockerfile: Dockerfile
    working_dir: /front
    networks:
      - jg
    ports:
      - 3000:3000
    volumes:
      - ./front/src:/my_front/src

  nginx:
    container_name: proxy
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
      - front
    environment:
      - SERVER_HOST=${SERVER_HOST}
    build: ./proxy
    networks:
      - jg
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./proxy/templates:/templates:ro
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

networks:
  jg:
    name: my_network
    driver: bridge